language: java
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS example;'
env: 
  - DATABASE=jdbc:mysql://localhost:3306/example DB_USERNAME=travis DB_PASSWORD=""
  
notifications:
  slack:
      on_succes: always
      on_failure: always
  email:
      one@example.com
      
